<robot name="car_arm" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Defining the colors used in this robot -->
    <!-- link1 properties -->
    <xacro:property name="PI" value="3.1415926" />

    <xacro:property name="link1_width" value="0.015" />
    <xacro:property name="link1_len" value="0.05" />
    <xacro:property name="link1_m" value="0.02" />
    <!-- link2 properties -->
    <xacro:property name="link2_width" value="0.01" />
    <xacro:property name="link2_len" value="0.09" />
    <xacro:property name="link2_m" value="0.02" />
    <!-- link3 properties -->
    <xacro:property name="link3_width" value="0.01" />
    <xacro:property name="link3_len" value="0.11" />
    <xacro:property name="link3_m" value="0.02" />
    <!-- link4 properties -->
    <xacro:property name="link4_width" value="0.01" />
    <xacro:property name="link4_len" value="0.03" />
    <xacro:property name="link4_m" value="0.02" />
    <!-- link5 properties -->
    <xacro:property name="link5_width" value="0.035" />
    <xacro:property name="link5_len" value="0.005" />
    <xacro:property name="link5_m" value="0.02" />
    <!-- Left gripper -->
    <xacro:property name="left_gripper_len" value="0.1" />
    <xacro:property name="left_gripper_width" value="0.01" />
    <xacro:property name="left_gripper_h" value="0.02" />
    <xacro:property name="left_gripper_m" value="0.02" />
    <!-- Right gripper -->
    <xacro:property name="right_gripper_len" value="0.1" />
    <xacro:property name="right_gripper_width" value="0.005" />
    <xacro:property name="right_gripper_h" value="0.02" />
    <xacro:property name="right_gripper_m" value="0.02" />
    <!-- Gripper frame -->
    <xacro:property name="grasp_frame_radius" value="0.001" />
    <!-- /////////////////////////////////////   LINK1  ////////////////////////////////////////////// -->
    <link name="link1" >
        <visual>
            <origin xyz="0 0 ${link1_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link1_width}" length="${link1_len}"/>
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0  0 ${link1_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link1_width}" length="${link1_len}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${link1_m}" r="${link1_width}" h="${link1_len}" />
    </link>
    <joint name="joint1" type="revolute">
        <parent link="base_link"/>
        <child link="link1"/>
        <origin xyz="0.05 0 ${base_link_h / 2 + 0.01}" rpy="0 0 0" />
        <!-- <origin xyz="0.05 0.03 ${base_link_h / 2 + 0.01}" rpy="0 0 0" /> -->
        <axis xyz="0 0 1" />
        <limit effort="300" velocity="1" lower="-2.96" upper="2.96"/>
        
    </joint>
    <link name="link2" >
        <visual>
            <origin xyz="0 0 ${link2_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link2_width}" length="${link2_len}"/>
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <origin xyz="0  0 ${link2_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link2_width}" length="${link2_len}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${link2_m}" r="${link2_width}" h="${link2_len}" />
    </link>
    <joint name="joint2" type="revolute">
        <parent link="link1"/>
        <child link="link2"/>
        <origin xyz="0 0 ${link1_len+0.01}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="300" velocity="1" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>
    <link name="link3" >
        <visual>
            <origin xyz="0 0 ${link3_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link3_width}" length="${link3_len}"/>
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0  0 ${link3_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link3_width}" length="${link3_len}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${link3_m}" r="${link3_width}" h="${link3_len}" />
    </link>
    <joint name="joint3" type="revolute">
        <parent link="link2"/>
        <child link="link3"/>
        <origin xyz="0 0 ${link2_len+0.01}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="300" velocity="1" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>
    <link name="link4" >
        <visual>
            <origin xyz="0 0 ${link4_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link4_width}" length="${link4_len}"/>
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <origin xyz="0  0 ${link4_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link4_width}" length="${link4_len}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${link4_m}" r="${link4_width}" h="${link4_len}" />
    </link>
    <joint name="joint4" type="revolute">
        <parent link="link3"/>
        <child link="link4"/>
        <origin xyz="0 0 ${link3_len+0.01}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="300" velocity="1" lower="${-PI/2}" upper="${PI/2}"/>
    </joint>
    <link name="link5" >
        <visual>
            <origin xyz="0 0 ${link5_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link5_width}" length="${link5_len}"/>
            </geometry>
            <material name="light_blue" />
        </visual>
        <collision>
            <origin xyz="0  0 ${link5_len/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${link5_width}" length="${link5_len}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${link5_m}" r="${link5_width}" h="${link5_len}" />
    </link>
    <joint name="joint5" type="revolute">
        <parent link="link4"/>
        <child link="link5"/>
        <origin xyz="0 0 ${link4_len}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="300" velocity="1" lower="${-PI}" upper="${PI}"/>
    </joint>
    <link name="left_gripper" >
        <visual>
            <origin xyz="0 0 ${left_gripper_len/2}" rpy="0 ${PI/2} 0" />
            <geometry>
                <box size="${left_gripper_len} ${left_gripper_width} ${left_gripper_h}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <origin xyz="0 0 ${left_gripper_len/2}" rpy="0 ${PI/2} 0" />
            <geometry>
                <box size="${left_gripper_len} ${left_gripper_width} ${left_gripper_h}" />
            </geometry>
        </collision>
        <xacro:Box_inertial_matrix m="${left_gripper_m}" l="${left_gripper_len}" w="${left_gripper_width}" h="${left_gripper_h}" />
    </link>
    <joint name="left_gripper_joint" type="prismatic">
        <parent link="link5"/>
        <child link="left_gripper"/>
        <origin xyz="0 0.03 ${link5_len}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="100" lower="0" upper="0.05" velocity="1.0"/>
    </joint>
    <link name="right_gripper" >
        <visual>
            <origin xyz="0 0 ${right_gripper_len/2}" rpy="0 ${PI/2} 0" />
            <geometry>
                <box size="${right_gripper_len} ${right_gripper_width} ${right_gripper_h}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <origin xyz="0 0 ${right_gripper_len/2}" rpy="0 ${PI/2} 0" />
            <geometry>
                <box size="${right_gripper_len} ${right_gripper_width} ${right_gripper_h}" />
            </geometry>
        </collision>
        <xacro:Box_inertial_matrix m="${right_gripper_m}" l="${right_gripper_len}" w="${right_gripper_width}" h="${right_gripper_h}" />
    </link>
    <joint name="right_gripper_joint" type="prismatic">
        <parent link="link5"/>
        <child link="right_gripper"/>
        <origin xyz="0 -0.03 ${link5_len}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="100" lower="0" upper="0.05" velocity="1.0"/>
    </joint>
    <link name="grasping_frame"/>
    <joint name="grasping_frame_joint" type="fixed">
        <parent link="link5"/>
        <child link="grasping_frame"/>
        <origin xyz="0 0 ${link5_len}" rpy="0 0 0"/>
    </joint>
    <gazebo reference="link1">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="link2">
        <material>Gazebo/White</material>
    </gazebo>
    <gazebo reference="link3">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="link4">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="link5">
        <material>Gazebo/White</material>
    </gazebo>
    <gazebo reference="left_gripper">
        <mu1>1000</mu1>
        <mu2>1000</mu2>
        <kp>1000000.0</kp>
        <kd>100000.0</kd>
        <slip1>0</slip1>
        <slip2>0</slip2>
        <minDepth>0.001</minDepth>
        <maxVel>0</maxVel>
        <torsional>
            <ode>
                <coefficient>1000</coefficient>
                <slip>0</slip>
            </ode>
        </torsional>
    </gazebo>
    <gazebo reference="right_gripper">
        <mu1>1000</mu1>
        <mu2>1000</mu2>
        <kp>1000000.0</kp>
        <kd>100000.0</kd>
        <slip1>0</slip1>
        <slip2>0</slip2>
        <minDepth>0.001</minDepth>
        <maxVel>0</maxVel>
        <torsional>
            <ode>
                <coefficient>1000</coefficient>
                <slip>0</slip>
            </ode>
        </torsional>
    </gazebo>
    <xacro:macro name="transmission_block" params="joint_name">
        <transmission name="tran${joint_name}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="joint${joint_name}">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            </joint>
            <actuator name="motor${joint_name}">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>
    <xacro:transmission_block joint_name="1"/>
    <xacro:transmission_block joint_name="2"/>
    <xacro:transmission_block joint_name="3"/>
    <xacro:transmission_block joint_name="4"/>
    <xacro:transmission_block joint_name="5"/>
    <transmission name="tran_right_gripper_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_gripper_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_right_gripper_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="tran_left_gripper_joint">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_gripper_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor_gripper_joint">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin>
    </gazebo>
    <!-- <gazebo>
    <plugin name="gazebo_grasp_fix" filename="libgazebo_grasp_fix.so">
        <arm>
           <arm_name>gri</arm_name>
           <palm_link> link5 </palm_link>
           <gripper_link> left_gripper</gripper_link>
           <gripper_link> right_gripper</gripper_link>
        </arm>
       <forces_angle_tolerance>100</forces_angle_tolerance>
       <update_rate>50</update_rate>
       <grip_count_threshold>1</grip_count_threshold>
       <max_grip_count>2</max_grip_count>
       <release_tolerance>0.03</release_tolerance>
       <disable_collisions_on_attach>false</disable_collisions_on_attach>
       <contact_topic>__default_topic__</contact_topic>
    </plugin>
</gazebo> -->
</robot>