<robot name="my_base" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.14159"/>
    <xacro:property name="base_footprint_radius" value="0.001" />
    <xacro:property name="base_link_l" value="0.2" />
    <xacro:property name="base_link_w" value="0.15" />
    <xacro:property name="base_link_h" value="0.05" />
    <xacro:property name="heavy_link_l" value="0.05" />
    <xacro:property name="heavy_link_w" value="0.15" />
    <xacro:property name="heavy_link_h" value="0.06" />
    <xacro:property name="heavy_link_m" value="0.5" />
    <xacro:property name="earth_space" value="0.016" />
    <!-- 离地间距 -->
    <xacro:property name="base_link_m" value="1.5" />
    <!-- 底盘 -->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${base_footprint_radius}" />
            </geometry>
        </visual>
    </link>
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_link_l} ${base_link_w} ${base_link_h}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="white">
                <color rgba="0.5 0.3 0.0 0.5" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${base_link_l} ${base_link_w} ${base_link_h}" />
                <origin xyz="0 0 0" rpy="0 0 0" />
            </geometry>
        </collision>
        <xacro:Box_inertial_matrix m="${base_link_m}" l="${base_link_l}" w="${base_link_w}" h="${base_link_h}" />
    </link>
    <joint name="base_link2base_footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${earth_space + base_link_h / 2 }" />
    </joint>
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    <link name="heavy_link">
        <visual>
            <geometry>
                <box size="${heavy_link_l} ${heavy_link_w} ${heavy_link_h}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="white">
                <color rgba="0.5 0.3 0.0 0.5" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${heavy_link_l} ${heavy_link_w} ${heavy_link_h}" />
                <origin xyz="0 0 0" rpy="0 0 0" />
            </geometry>
        </collision>
        <xacro:Box_inertial_matrix m="${heavy_link_m}" l="${heavy_link_l}" w="${heavy_link_w}" h="${heavy_link_h}" />
    </link>
    <joint name="heavy_link2base_link" type="fixed">
        <parent link="base_link" />
        <child link="heavy_link" />
        <origin xyz="${-(base_link_l / 2 -heavy_link_l/2)} 0 ${base_link_h / 2+ heavy_link_h / 2 }" />
    </joint>
    <gazebo reference="heavy_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    <!-- 驱动轮 -->
    <xacro:property name="wheel_radius" value="0.03" />
    <xacro:property name="wheel_length" value="0.035" />
    <xacro:property name="wheel_m" value="0.1" />
    <xacro:macro name="add_wheels" params="name flag">
        <link name="${name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
                <material name="black" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
            </collision>
            <xacro:cylinder_inertial_matrix m="${wheel_m}" r="${wheel_radius}" h="${wheel_length}" />
        </link>
        <joint name="${name}_wheel2base_link" type="continuous">
            <parent link="base_link" />
            <child link="${name}_wheel" />
            <origin xyz="0 ${flag * base_link_w/2} ${-(earth_space + base_link_h / 2 - wheel_radius) }" />
            <axis xyz="0 1 0" />
        </joint>
        <gazebo reference="${name}_wheel">
            <material>Gazebo/Black</material>
            <mu1>100000000</mu1>
            <mu2>100000000</mu2>
            <kp>100000000</kp>
            <kd>1</kd>
        </gazebo>
    </xacro:macro>
    <xacro:add_wheels name="left" flag="1" />
    <xacro:add_wheels name="right" flag="-1" />
    <xacro:property name="support_wheel_radius" value="0.008" />
    <xacro:property name="support_wheel_distance" value="0.03" />
    <xacro:property name="support_wheel_m" value="0.03" />
    <!-- 支撑轮宏 -->
    <xacro:macro name="add_support_wheel" params="name flag number" >
        <link name="${name}_wheel_${number}">
            <visual>
                <geometry>
                    <sphere radius="${support_wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="black" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${support_wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertial_matrix m="${support_wheel_m}" r="${support_wheel_radius}" />
        </link>
        <joint name="${name}_wheel2base_link_${number}" type="continuous">
            <parent link="base_link" />
            <child link="${name}_wheel_${number}" />
            <origin xyz="${flag * (base_link_l / 2 - support_wheel_distance)} ${-0.05*(number-1)-0.05*(number-2)} ${-(base_link_h / 2 + support_wheel_radius)}" />
            <axis xyz="1 1 1" />
        </joint>
        <gazebo reference="${name}_wheel_${number}">
            <material>Gazebo/Black</material>
            <kp>100000000</kp>
            <kd>1</kd>
        </gazebo>
    </xacro:macro>
    <xacro:add_support_wheel name="front" flag="1" number="1"/>
    <xacro:add_support_wheel name="front" flag="1" number="2"/>
    <xacro:add_support_wheel name="back" flag="-1" number="1"/>
    <xacro:add_support_wheel name="back" flag="-1" number="2"/>
</robot>