/:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5

    gains:
      joint1: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint2: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint3: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint4: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint5: {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}



  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
    - right_gripper_joint
    - left_gripper_joint
    gains:
      right_gripper_joint: {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}
      left_gripper_joint: {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}


  mobile_base_controller:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: 'left_wheel2base_link'
    right_wheel: 'right_wheel2base_link'
    publish_rate: 50.0 # default: 50
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation: 0.15
    wheel_radius: 0.03

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier: 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.25
    enable_odom_tf: false
    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0 # m/s
        min_velocity: -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration: 0.8 # m/s^2
        min_acceleration: -0.4 # m/s^2
        has_jerk_limits: true
        max_jerk: 5.0 # m/s^3
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.7 # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.5 # rad/s^2
        has_jerk_limits: true
        max_jerk: 2.5 # rad/s^3
