# For parameter descriptions, please refer to the template parameter files for each node.

ekf_se_odom:
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: true
  transform_time_offset: 0.0
  transform_timeout: 0.0
  print_diagnostics: true
  debug: false

  odom_frame: odom
  base_link_frame: base_footprint
  world_frame: odom

  odom0: /mobile_base_controller/odom
  # odom0_config: [false, false, false, false, false, false, true, true, true, false, false, true, false, false, false]
  odom0_config: [true, true, false, false, false, false, true, true, false, false, false, false, false, false, false]
  # odom0_config: [true, true, false, true, true, true, true, true, false, true, true, false, true, true, true]
  # odom0_config: [false, true, false, false, false, false, true, true, false, false, false, true, false, false, false]

  odom0_queue_size: 10
  odom0_nodelay: true
  odom0_differential: false
  odom0_relative: false

  imu0: /imu
  # imu0_config: [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true]
  imu0_config: [false, false, false, true, true, false, true, true, true, true, true, true, false, false, false]
  # imu0_config: [true, true, false, true, false, false, true, true, false, true, true, true, false, false, true]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: false
  imu0_queue_size: 10
  imu0_remove_gravitational_acceleration: true

  use_control: false

  # process_noise_covariance: [1e-3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.3]

  # initial_estimate_covariance: [1e-9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0]


  # odom_frame: odom
  # base_link_frame: base_footprint
  # world_frame: odom

  # two_d_mode: true

  # frequency: 30
  # sensor_timeout: 0.1

  # # Configure which sensors are being used
  # odom0: /mobile_base_controller/odom
  # imu0: /imu

  # # Configure sensor processing parameters
  # odom0_config: [true, true, false, false, false, true, false, false, false, false, false, false, false, false, false]
  # imu0_config: [false, false, false, true, true, true, true, true, true, true, true, true, true, true, true]

  # # Specify sensor noise parameters
  # odom0_differential: false
  # odom0_relative: false
  # imu0_differential: false
  # imu0_relative: false

  # # Odometry and IMU data noise values
  # odom0_pose_noise_cov: [1e-3, 0, 0, 0, 0, 0, 0, 1e-3, 0, 0, 0, 0, 0, 0, 1e-6, 0, 0, 0, 0, 0, 0, 1e-6, 0, 0, 0, 0, 0, 0, 1e-6, 0, 0, 0, 0, 0, 0, 1e-3]

  # imu0_angular_velocity_noise_cov: [1e-6, 0, 0, 0, 1e-6, 0, 0, 0, 1e-6]

  # imu0_linear_acceleration_noise_cov: [1e-6, 0, 0, 0, 1e-6, 0, 0, 0, 1e-6]
